"""rename_keyword_table_to_subscription

Revision ID: 49a375bdc260
Revises: 4e0246d1cadf
Create Date: 2022-05-31 11:18:26.010287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a375bdc260'
down_revision = '4e0246d1cadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=True),
    sa.Column('subscriber', sa.String(length=255), nullable=True),
    sa.Column('word', sa.String(length=255), nullable=True),
    sa.Column('unsubscribed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['channel_name'], ['channel.channel_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('keyword')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subscriber', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('word', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('channel_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('unsubscribed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['channel_name'], ['channel.channel_name'], name='keyword_channel_name_fkey'),
    sa.PrimaryKeyConstraint('id', name='keyword_pkey')
    )
    op.drop_table('subscription')
    # ### end Alembic commands ###
