"""rename_active_column_of_keyword_table_to_unsubscribed

Revision ID: 4e0246d1cadf
Revises: 4fe7d3e609e2
Create Date: 2022-05-31 09:05:38.186661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0246d1cadf'
down_revision = '4fe7d3e609e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keyword', sa.Column('unsubscribed', sa.Boolean(), nullable=True))
    op.drop_column('keyword', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keyword', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('keyword', 'unsubscribed')
    # ### end Alembic commands ###
