"""Add channel table

Revision ID: 4fe7d3e609e2
Revises: 01edc2603646
Create Date: 2022-05-27 13:54:58.486150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fe7d3e609e2'
down_revision = '01edc2603646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('channel_name')
    )
    op.add_column('keyword', sa.Column('channel_name', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'keyword', 'channel', ['channel_name'], ['channel_name'])
    op.drop_column('keyword', 'channel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keyword', sa.Column('channel', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'keyword', type_='foreignkey')
    op.drop_column('keyword', 'channel_name')
    op.drop_table('channel')
    # ### end Alembic commands ###
