"""Add keyword table

Revision ID: a5beef0a0d51
Revises: 
Create Date: 2022-05-23 14:25:36.668591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5beef0a0d51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.String(length=255), nullable=True),
    sa.Column('subscriber', sa.String(length=255), nullable=True),
    sa.Column('word', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyword')
    # ### end Alembic commands ###
