"""rename_word_column_of_subscription_table_to_keyword

Revision ID: e306363461d7
Revises: 49a375bdc260
Create Date: 2022-05-31 11:51:58.871773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e306363461d7'
down_revision = '49a375bdc260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('keyword', sa.String(length=255), nullable=True))
    op.drop_column('subscription', 'word')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('word', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('subscription', 'keyword')
    # ### end Alembic commands ###
