"""Add subsription_view

Revision ID: f85359967c92
Revises: eb748a2d1c9c
Create Date: 2022-07-01 12:13:26.934345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f85359967c92"
down_revision = "eb748a2d1c9c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription_view",
        sa.Column("channel_name", sa.String(length=255), nullable=True),
        sa.Column("subscriber", sa.String(length=255), nullable=True),
        sa.Column("keyword", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscription_view")
    # ### end Alembic commands ###
